# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-21 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='product_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
