# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-23 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_authentication_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='online_course_dispatch',
            field=models.BooleanField(default=True),
        ),
    ]
