# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-21 21:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20170926_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='username',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
